import { useEffect, useState } from 'react';
import { Archive, BarChart3, CalendarPlus, CheckCircle, ClipboardCheck, FileBadge, LogOut, Megaphone, Search, ShieldCheck, Ticket, Users, X } from 'lucide-react';

const tabs = [
  ['overview', 'Overview', BarChart3], ['events', 'Events', CalendarPlus], ['registrations', 'Registrations', Ticket], ['members', 'Members', Users],
  ['requests', 'Requests', ClipboardCheck], ['announcements', 'Notices', Megaphone], ['auditions', 'Auditions', ShieldCheck],
  ['attendance', 'Attendance', CheckCircle], ['certificates', 'Certificates', FileBadge], ['archive', 'Archive', Archive], ['notifications', 'Notifications', Megaphone],
];

function Stat({ label, value }) { return <div className="rounded-xl bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-3xl font-bold text-haryana-dark">{value}</p></div>; }
function Field({ label, ...props }) { return <label className="block text-sm font-semibold text-gray-700">{label}<input {...props} className="mt-1 w-full rounded border border-gray-200 p-3 font-normal" /></label>; }

export default function Dashboard({ api, user, token, pendingRegistration, onClose, onLogout }) {
  const isAdmin = user.role === 'admin' || user.role === 'coordinator';
  const [tab, setTab] = useState(isAdmin ? 'overview' : 'events');
  const [events, setEvents] = useState([]);
  const [registrations, setRegistrations] = useState([]);
  const [allRegistrations, setAllRegistrations] = useState([]);
  const [registrationCategory, setRegistrationCategory] = useState('');
  const [analytics, setAnalytics] = useState({});
  const [members, setMembers] = useState([]);
  const [requests, setRequests] = useState([]);
  const [announcements, setAnnouncements] = useState([]);
  const [auditions, setAuditions] = useState([]);
  const [auditionsLive, setAuditionsLive] = useState(false);
  const [attendance, setAttendance] = useState({ registered: 0, present: 0, absent: 0, percentage: 0 });
  const [archive, setArchive] = useState([]);
  const [notifications, setNotifications] = useState([]);
  const [certificateForm, setCertificateForm] = useState({ userId: '', eventId: '' });
  const [archiveForm, setArchiveForm] = useState({ title: '', category: 'Dance', year: new Date().getFullYear(), description: '', mediaUrl: '' });
  const [registrationEvent, setRegistrationEvent] = useState(null);
  const [notice, setNotice] = useState('');
  const [search, setSearch] = useState('');
  const [eventForm, setEventForm] = useState({ title: '', venue: '', startsAt: '', description: '', registrationDeadline: '', seatLimit: '' });

  function load() {
    api('/events').then(data => setEvents(data.events)).catch(() => setEvents([]));
    api('/me/registrations', { token }).then(data => setRegistrations(data.registrations)).catch(() => setRegistrations([]));
    if (isAdmin) {
      api(`/admin/registrations${registrationCategory ? `?category=${encodeURIComponent(registrationCategory)}` : ''}`, { token }).then(data => setAllRegistrations(data.registrations)).catch(() => setAllRegistrations([]));
      api('/admin/analytics', { token }).then(setAnalytics).catch(() => setAnalytics({}));
      api('/members', { token }).then(data => setMembers(data.members)).catch(() => setMembers([]));
      api('/admin/requests', { token }).then(data => setRequests(data.requests)).catch(() => setRequests([]));
      api('/announcements').then(data => setAnnouncements(data.announcements)).catch(() => setAnnouncements([]));
      api('/admin/auditions', { token }).then(data => setAuditions(data.auditions)).catch(() => setAuditions([]));
      api('/auditions/status').then(data => setAuditionsLive(data.auditionStatus.live)).catch(() => setAuditionsLive(false));
      api('/archive').then(data => setArchive(data.archive)).catch(() => setArchive([]));
      api('/notifications', { token }).then(data => setNotifications(data.notifications)).catch(() => setNotifications([]));
    }
  }
  useEffect(load, [token, registrationCategory]);
  useEffect(() => { if (pendingRegistration && !isAdmin) action(() => api(`/events/${pendingRegistration.eventId}/register`, { method: 'POST', token, body: { category: pendingRegistration.category } }), `Registered for ${pendingRegistration.category}. Your QR pass is ready in your registrations.`); }, [pendingRegistration, isAdmin]);
  async function action(work, success = 'Saved.') { try { await work(); setNotice(success); load(); } catch (error) { setNotice(error.message); } }
  async function createEvent(event) { event.preventDefault(); await action(() => api('/events', { method: 'POST', token, body: eventForm }), 'Event created.'); setEventForm({ title: '', venue: '', startsAt: '', description: '', registrationDeadline: '', seatLimit: '' }); }
  function register(eventId, category) { action(() => api(`/events/${eventId}/register`, { method: 'POST', token, body: { category } }), `Registered for ${category}. Your QR pass is ready in your registrations.`); setRegistrationEvent(null); }
  function markRequest(id, status) { action(() => api(`/admin/requests/${id}`, { method: 'PATCH', token, body: { status } })); }
  function changeRole(id, role) { action(() => api(`/members/${id}/role`, { method: 'PATCH', token, body: { role } }), 'Role updated.'); }
  function changeAudition(id, status) { action(() => api(`/admin/auditions/${id}`, { method: 'PATCH', token, body: { status } }), 'Audition updated.'); }
  function toggleAuditions() { action(() => api('/admin/auditions/status', { method: 'PATCH', token, body: { live: !auditionsLive } }).then(() => setAuditionsLive(!auditionsLive)), auditionsLive ? 'Auditions closed.' : 'Auditions are live.'); }
  function loadAttendance(eventId) { api(`/events/${eventId}/attendance`, { token }).then(setAttendance).catch(() => setAttendance({ registered: 0, present: 0, absent: 0, percentage: 0 })); }
  async function issueCertificate(event) { event.preventDefault(); await action(() => api('/admin/certificates', { method: 'POST', token, body: certificateForm }), 'Certificate created with a verification QR payload.'); }
  async function createArchiveItem(event) { event.preventDefault(); await action(() => api('/admin/archive', { method: 'POST', token, body: archiveForm }), 'Archive item added.'); setArchiveForm({ title: '', category: 'Dance', year: new Date().getFullYear(), description: '', mediaUrl: '' }); }

  return <div className="fixed inset-0 z-[60] overflow-y-auto bg-haryana-cream"><div className="mx-auto min-h-screen max-w-[1400px] px-4 py-8 sm:px-8 lg:px-12"><header className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-bold uppercase tracking-[.2em] text-haryana-red"><ShieldCheck size={17} /> {isAdmin ? 'Management workspace' : 'Member workspace'}</p><h1 className="mt-2 text-4xl font-bold text-haryana-dark">{isAdmin ? 'Mandli control center' : `Namaste, ${user.name || 'member'}`}</h1></div><div className="flex gap-2"><button onClick={onClose} className="rounded border border-haryana-dark/20 p-2 text-haryana-dark" aria-label="Close dashboard"><X /></button><button onClick={onLogout} className="flex items-center gap-2 rounded bg-haryana-dark px-4 py-2 text-sm font-semibold text-white"><LogOut size={16} /> Log out</button></div></header>
      <div className="mb-8 flex gap-2 overflow-x-auto border-b border-haryana-dark/10 pb-2">{(isAdmin ? tabs : [['events', 'Events', Ticket], ['profile', 'Profile', Users]]).map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-2 rounded px-4 py-2 text-sm font-semibold ${tab === id ? 'bg-haryana-dark text-white' : 'text-haryana-dark hover:bg-white'}`}><Icon size={16} /> {label}</button>)}</div>
      {notice && <div className="mb-5 flex items-center justify-between rounded bg-haryana-dark px-4 py-3 text-sm text-white"><span>{notice}</span><button onClick={() => setNotice('')} aria-label="Dismiss message"><X size={16} /></button></div>}
      {registrationEvent && !isAdmin && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-md rounded-xl bg-white p-7"><div className="flex items-start justify-between"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-haryana-red">Registration</p><h2 className="mt-2 text-2xl font-bold text-haryana-dark">{registrationEvent.title}</h2></div><button onClick={() => setRegistrationEvent(null)} aria-label="Close registration options" className="text-gray-500"><X /></button></div><p className="mt-5 text-gray-600">Choose your participation category:</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{['Dance', 'Dramatic', 'Music', 'Theatre', 'Fine Arts'].map(category => <button key={category} onClick={() => register(registrationEvent.id, category)} className="rounded border border-haryana-red/20 px-4 py-3 text-left font-semibold text-haryana-dark hover:bg-haryana-cream">{category}</button>)}</div></div></div>}
      {tab === 'overview' && <section><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Stat label="Members" value={analytics.members || 0} /><Stat label="Events" value={analytics.events || 0} /><Stat label="Registrations" value={analytics.registrations || 0} /><Stat label="Active events" value={analytics.activeEvents || 0} /><Stat label="Present scans" value={analytics.attendance || 0} /></div><div className="mt-8 rounded-xl bg-white p-6"><h2 className="text-2xl font-bold text-haryana-dark">Platform status</h2><p className="mt-2 text-gray-600">The dashboard is connected to the protected API and persistent data store. Use the tabs to manage the society.</p></div></section>}
      {tab === 'registrations' && <section><div className="mb-5 flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-bold text-haryana-dark">Event registrations</h2><p className="mt-1 text-gray-600">Student selections collected from every event form.</p></div><select value={registrationCategory} onChange={event => setRegistrationCategory(event.target.value)} className="rounded border border-gray-200 p-3"><option value="">All categories</option><option>Dance</option><option>Dramatic</option><option>Music</option><option>Theatre</option><option>Fine Arts</option></select></div><div className="overflow-x-auto rounded-xl bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-gray-500"><tr><th className="p-4">Student</th><th className="p-4">Email</th><th className="p-4">Event</th><th className="p-4">Category</th><th className="p-4">Registration ID</th><th className="p-4">Date</th></tr></thead><tbody>{allRegistrations.length === 0 ? <tr><td colSpan="6" className="p-8 text-center text-gray-600">No student registrations yet.</td></tr> : allRegistrations.map(registration => <tr key={registration.id} className="border-b last:border-0"><td className="p-4 font-semibold text-haryana-dark">{registration.student}</td><td className="p-4">{registration.email}</td><td className="p-4">{registration.event}</td><td className="p-4"><span className="rounded-full bg-haryana-cream px-3 py-1 font-semibold text-haryana-red">{registration.category}</span></td><td className="p-4 font-mono text-xs">{registration.registrationId}</td><td className="p-4">{new Date(registration.registeredAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></section>}
      {tab === 'events' && <section><div className="mb-6 flex items-center justify-between"><h2 className="text-2xl font-bold text-haryana-dark">{isAdmin ? 'Manage events' : 'Upcoming events'}</h2></div>{isAdmin && <form onSubmit={createEvent} className="mb-8 grid gap-4 rounded-xl bg-white p-6 md:grid-cols-2"><Field label="Event title" required value={eventForm.title} onChange={e => setEventForm({ ...eventForm, title: e.target.value })} /><Field label="Venue" required value={eventForm.venue} onChange={e => setEventForm({ ...eventForm, venue: e.target.value })} /><Field label="Date and time" required type="datetime-local" value={eventForm.startsAt} onChange={e => setEventForm({ ...eventForm, startsAt: e.target.value })} /><Field label="Registration deadline" type="datetime-local" value={eventForm.registrationDeadline} onChange={e => setEventForm({ ...eventForm, registrationDeadline: e.target.value })} /><Field label="Seat limit" type="number" min="0" value={eventForm.seatLimit} onChange={e => setEventForm({ ...eventForm, seatLimit: e.target.value })} /><label className="text-sm font-semibold text-gray-700">Description<textarea required className="mt-1 w-full rounded border border-gray-200 p-3 font-normal" rows="2" value={eventForm.description} onChange={e => setEventForm({ ...eventForm, description: e.target.value })} /></label><button className="rounded bg-haryana-red px-5 py-3 font-semibold text-white md:col-span-2">Create event</button></form>}<div className="grid gap-5 lg:grid-cols-2">{events.length === 0 ? <div className="rounded-xl bg-white p-8 text-gray-600">No events published yet.</div> : events.map(event => <article key={event.id} className="rounded-xl bg-white p-6 shadow-sm"><div className="flex justify-between gap-4"><div><p className="text-sm font-semibold text-haryana-red">{new Date(event.startsAt).toLocaleString()}</p><h3 className="mt-2 text-2xl font-bold text-haryana-dark">{event.title}</h3><p className="mt-1 text-gray-500">{event.venue}</p></div><Ticket className="text-haryana-red" /></div><p className="mt-4 text-gray-600">{event.description}</p>{!isAdmin && <button onClick={() => setRegistrationEvent(event)} className="mt-5 flex items-center gap-2 rounded bg-haryana-dark px-4 py-2 text-sm font-semibold text-white"><CheckCircle size={16} /> Register</button>}</article>)}</div></section>}
      {tab === 'profile' && <section className="max-w-3xl rounded-xl bg-white p-8"><h2 className="text-3xl font-bold text-haryana-dark">My profile</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Stat label="Name" value={user.name} /><Stat label="Email" value={user.email} /><Stat label="Role" value={user.role} /><Stat label="Branch" value={user.branch || 'Not specified'} /><Stat label="Roll No" value={user.rollNo || 'Not specified'} /><Stat label="Year" value={user.year || 'Not specified'} /><Stat label="Mobile No" value={user.phone || 'Not specified'} /><Stat label="Interest" value={user.interest || 'Not specified'} /><Stat label="Registered events" value={registrations.length} /></div></section>}
      {tab === 'members' && <section><div className="mb-5 flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3 w-full max-w-md"><Search className="text-gray-500" /><input value={search} onChange={e => { setSearch(e.target.value); api(`/members?search=${encodeURIComponent(e.target.value)}`, { token }).then(data => setMembers(data.members)); }} placeholder="Search name, branch, roll no, interest..." className="w-full rounded border border-gray-200 p-3 text-sm outline-none focus:border-haryana-red" /></div><span className="text-sm font-semibold text-gray-500">Total Mandli Members: {members.length}</span></div><div className="overflow-x-auto rounded-xl bg-white shadow-sm"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b bg-haryana-cream/50 text-gray-600 font-semibold"><tr><th className="p-4">Student Name</th><th className="p-4">Email</th><th className="p-4">Mobile No</th><th className="p-4">Branch</th><th className="p-4">Roll No</th><th className="p-4">Year</th><th className="p-4">Interest</th><th className="p-4">Role</th></tr></thead><tbody>{members.length === 0 ? <tr><td colSpan="8" className="p-8 text-center text-gray-600">No members match your search criteria.</td></tr> : members.map(member => <tr key={member.id} className="border-b last:border-0 hover:bg-gray-50 transition-colors"><td className="p-4 font-bold text-haryana-dark">{member.name}</td><td className="p-4 text-gray-600">{member.email}</td><td className="p-4 font-mono text-xs">{member.phone || '—'}</td><td className="p-4"><span className="rounded bg-gray-100 px-2.5 py-1 text-xs font-semibold text-gray-700">{member.branch || '—'}</span></td><td className="p-4 font-mono text-xs text-gray-600">{member.rollNo || '—'}</td><td className="p-4 text-xs font-medium text-gray-600">{member.year || '—'}</td><td className="p-4"><span className="rounded-full bg-haryana-cream px-3 py-1 text-xs font-bold text-haryana-red">{member.interest || 'General'}</span></td><td className="p-4"><select value={member.role} onChange={e => changeRole(member.id, e.target.value)} className="rounded border border-gray-200 p-1.5 text-xs font-semibold"><option>member</option><option>coordinator</option><option>visitor</option></select></td></tr>)}</tbody></table></div></section>}
      {tab === 'requests' && <section><h2 className="mb-5 text-2xl font-bold text-haryana-dark">Contact requests</h2><div className="space-y-4">{requests.map(request => <article key={request.id} className="rounded-xl bg-white p-5"><div className="flex justify-between gap-4"><div><h3 className="font-bold text-haryana-dark">{request.name}</h3><p className="text-sm text-haryana-red">{request.email}</p></div><span className="text-sm font-semibold">{request.status}</span></div><p className="mt-3 text-gray-600">{request.message}</p><button onClick={() => markRequest(request.id, request.status === 'Handled' ? 'Pending' : 'Handled')} className="mt-4 rounded bg-haryana-dark px-3 py-2 text-sm font-semibold text-white">Toggle status</button></article>)}</div></section>}
      {tab === 'announcements' && <section><h2 className="mb-5 text-2xl font-bold text-haryana-dark">Announcements</h2>{announcements.map(item => <article key={item.id} className="mb-4 rounded-xl bg-white p-5"><h3 className="font-bold text-haryana-dark">{item.title}</h3><p className="mt-2 text-gray-600">{item.content}</p></article>)}</section>}
      {tab === 'auditions' && <section><div className="mb-5 flex flex-wrap items-center justify-between gap-4"><h2 className="text-2xl font-bold text-haryana-dark">Audition review</h2><button onClick={toggleAuditions} className={`rounded px-4 py-2 text-sm font-semibold text-white ${auditionsLive ? 'bg-haryana-red' : 'bg-haryana-dark'}`}>{auditionsLive ? 'Close auditions' : 'Start auditions'}</button></div><p className="mb-5 text-sm text-gray-600">Public status: <strong>{auditionsLive ? 'Auditions are live' : 'Auditions are closed'}</strong></p>{auditions.map(item => <article key={item.id} className="mb-4 flex flex-wrap items-center justify-between gap-4 rounded-xl bg-white p-5"><div><h3 className="font-bold text-haryana-dark">{item.applicant}</h3><p className="text-sm text-gray-500">{item.email} · {item.category}</p></div><select value={item.status} onChange={e => changeAudition(item.id, e.target.value)} className="rounded border p-2"><option>Pending</option><option>Shortlisted</option><option>Selected</option><option>Rejected</option></select></article>)}</section>}
      {tab === 'attendance' && <section><h2 className="mb-5 text-2xl font-bold text-haryana-dark">Attendance management</h2><div className="mb-6 grid gap-3 sm:grid-cols-2">{events.map(event => <button key={event.id} onClick={() => loadAttendance(event.id)} className="rounded-xl bg-white p-4 text-left shadow-sm hover:border-haryana-red"><strong className="block text-haryana-dark">{event.title}</strong><span className="text-sm text-gray-500">{new Date(event.startsAt).toLocaleString()}</span></button>)}</div><div className="grid gap-4 sm:grid-cols-4"><Stat label="Registered" value={attendance.registered} /><Stat label="Present" value={attendance.present} /><Stat label="Absent" value={attendance.absent} /><Stat label="Attendance" value={`${attendance.percentage}%`} /></div></section>}
      {tab === 'certificates' && <section><h2 className="mb-5 text-2xl font-bold text-haryana-dark">Digital certificates</h2><form onSubmit={issueCertificate} className="mb-8 grid gap-4 rounded-xl bg-white p-6 sm:grid-cols-2"><label className="text-sm font-semibold">Member<select required value={certificateForm.userId} onChange={e => setCertificateForm({ ...certificateForm, userId: e.target.value })} className="mt-1 w-full rounded border p-3"><option value="">Choose member</option>{members.map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label className="text-sm font-semibold">Event<select required value={certificateForm.eventId} onChange={e => setCertificateForm({ ...certificateForm, eventId: e.target.value })} className="mt-1 w-full rounded border p-3"><option value="">Choose event</option>{events.map(event => <option key={event.id} value={event.id}>{event.title}</option>)}</select></label><button className="rounded bg-haryana-red px-4 py-3 font-semibold text-white sm:col-span-2">Generate certificate</button></form><p className="text-gray-600">Generated certificates receive a unique ID and verification QR payload through the backend.</p></section>}
      {tab === 'archive' && <section><h2 className="mb-5 text-2xl font-bold text-haryana-dark">Cultural archive</h2><form onSubmit={createArchiveItem} className="mb-8 grid gap-4 rounded-xl bg-white p-6 sm:grid-cols-2"><Field label="Title" required value={archiveForm.title} onChange={e => setArchiveForm({ ...archiveForm, title: e.target.value })} /><Field label="Year" required type="number" value={archiveForm.year} onChange={e => setArchiveForm({ ...archiveForm, year: e.target.value })} /><label className="text-sm font-semibold">Category<select value={archiveForm.category} onChange={e => setArchiveForm({ ...archiveForm, category: e.target.value })} className="mt-1 w-full rounded border p-3"><option>Dance</option><option>Theatre</option><option>Folk Music</option><option>Festivals</option><option>Competitions</option><option>Workshops</option></select></label><Field label="Media URL" value={archiveForm.mediaUrl} onChange={e => setArchiveForm({ ...archiveForm, mediaUrl: e.target.value })} /><label className="text-sm font-semibold sm:col-span-2">Description<textarea className="mt-1 w-full rounded border border-gray-200 p-3 font-normal" rows="2" value={archiveForm.description} onChange={e => setArchiveForm({ ...archiveForm, description: e.target.value })} /></label><button className="rounded bg-haryana-red px-4 py-3 font-semibold text-white sm:col-span-2">Add archive item</button></form><div className="grid gap-4 sm:grid-cols-2">{archive.map(item => <article key={item.id} className="rounded-xl bg-white p-5"><p className="text-sm font-semibold text-haryana-red">{item.category} · {item.year}</p><h3 className="mt-2 text-xl font-bold text-haryana-dark">{item.title}</h3><p className="mt-2 text-gray-600">{item.description}</p></article>)}</div></section>}
      {tab === 'notifications' && <section><h2 className="mb-5 text-2xl font-bold text-haryana-dark">Notifications</h2>{notifications.length === 0 ? <div className="rounded-xl bg-white p-8 text-gray-600">No notifications yet.</div> : notifications.map(item => <article key={item.id} className="mb-4 rounded-xl bg-white p-5"><h3 className="font-bold text-haryana-dark">{item.title}</h3><p className="mt-2 text-sm text-gray-500">{new Date(item.createdAt).toLocaleString()}</p></article>)}</section>}
      </div></div>;
}
